name: CI
on: [push, workflow_dispatch]
jobs:
build:
build
runs-on: windows-latest steps:
- name: Download
run:invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64 zip -OutFile ngrok zip
- name: Extract
run: Expand-Archive ngrok zip
- name: Auth
run: \ngrok\ngrokn.exe authtoken $Env:NGROK_AUTH_TOKEN
env:
NGROK_AUTH_TOKEN ${{ secrets NGROK_AUTH_TOKEN }}
- name: Enable TS
- run: Set-ltemProperty -Path "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" -name "fDenyTSConnections" -Valeurs
run: Enable-NetFirewallRule -DesplayGroup "Remote Desktop"
run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-Secure -AsPlainText "p@ssOrd!" -Force)
-name: CreaT Tunnel
run: \ngrok\ngrokn.exe tcp 3389
